name: Validate JSONs
on:
  push:
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_JSONS: /js/json/games.json,/js/json/apps.json,/js/json/bg.json,/js/json/hacks.json,/js/json/plugins.json,/js/json/say.json
